---
# tasks file for instance

- name: Creating instance 
  import_tasks: create_instance.yml 
  when: options.create_instance

- name: Deleting instance 
  import_tasks: delete_instance.yml
  when: options.delete_instance

- name: changing instance flavor 
  import_tasks: resize_vm.yml
  when: options.resize_vm